server:
  port: ${PORT}

spring:
  datasource:
    platform: postgres
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  sql:
    init:
      mode: always