server:
  port: ${PORT}

spring:
  datasource:
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  sql:
    init:
      mode: always