server:
  port: ${PORT}

spring:
  datasource:
    platform: postgres
    url: ${DB_URL:${SPRING_DATASOURCE_URL}}
    username: ${DB_USER:${SPRING_DATASOURCE_USERNAME}}
    password: ${DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

  sql:
    init:
      mode: always